### ISSUE TITLE
Android startScan seems to have an issue (Testing on Lollipop)

### ISSUE THREAD

**Issue by kartonki** [EddyVerbruggen/nativescript-bluetooth-demo#10]
Hi Eddy,
I am new to this nativescript and I have been trying to get your module running on Android, so far I have not been successful, I get the following console output when trying to scan Any Peripheral (or HRM)
JS: ------- scanCallback.onScanFailed errorCode: 3
JS: ------- scanCallback.onScanFailed errorMessage: Internal error

I've been trying to figure out the reason, until I tried this with iOS and it seems to work on that platform, I wonder if there is now some change on the plugin or Android or what's the case

my tns version is 1.7.0, I just cloned your demo and followed the readme, thanks for the feedback

**Comment by EddyVerbruggen** [comment]
Hi, sorry to hear it's not working for you.

I've just update the demo app dependencies to the latest versions but I doubt that will help you.

The error you're seeing is [this one](http://developer.android.com/reference/android/bluetooth/le/ScanCallback.html#SCAN_FAILED_INTERNAL_ERROR), perhaps you can google it because it may be specific to your Android device. Which one is it by the way (and does it have Bluetooh LE support)?

**Comment by kartonki** [comment]
Thanks for the reply,
I had also tried to upgrade the dependencies to no avail before your commit, but thanks as well for doing that too.

Thanks for pointing me to the google page, and also for asking about the device, it is a Nexus 7, and for sure, there's a model that has BLE and one that doesn't, so I think I have the one without the proper support, will try to get my hands on a different device.

So, with the likelihood that I have outdated HW, I suggest you close this issue, sorry for opening it without checking the basics first

**Comment by EddyVerbruggen** [comment]
Ah, I have a Nexus 7 (old model, 2012) as well and that doesn't support BLE. My Samsung PRO8 tablet does though. Thanks for the update!
